---
# This is the handler file of mywebserver

- name: Restart the httpd service
  service:
    name: httpd
    state: restarted

- name: Restart the firewalld service
  service: 
    name: firewalld
    state: restarted

